// <auto-generated />
using System;
using Infomercado.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infomercado.Domain.Migrations
{
    [DbContext(typeof(InfoMercadoDbContext))]
    [Migration("20210711170528_AddEncargos")]
    partial class AddEncargos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infomercado.Domain.Models.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("NomeEmpresarial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Cnpj");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contabilizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AjusteAlivioRetroativo")
                        .HasColumnType("float");

                    b.Property<double>("AjusteExposicaoFinanceira")
                        .HasColumnType("float");

                    b.Property<double>("AjusteMcsd")
                        .HasColumnType("float");

                    b.Property<double>("AjusteRecontabilizacoes")
                        .HasColumnType("float");

                    b.Property<double>("CompensacaoMre")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoCcearUsinasAptas")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContracaoPorDisponibilidade")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContratacaoComercializacaoEnergiaNuclear")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContratacaoCotaGarantiaFisica")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContratacaoItaipu")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoCustosDeslocamentoPldeCmo")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoRepasseRiscoHidrologico")
                        .HasColumnType("float");

                    b.Property<double>("EncargosConsolidados")
                        .HasColumnType("float");

                    b.Property<double>("ExcedenteFinanceiroEnergiaReserva")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<double>("ResultadoFinal")
                        .HasColumnType("float");

                    b.Property<double>("ResultadoMercadoCurtoPrazo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdPerfilAgente", "MesAno");

                    b.ToTable("Contabilizacaes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ContratacaoMWm")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdPerfilAgente", "Data", "Tipo");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.DadosGeracaoUsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CapacidadeUsinaMW")
                        .HasColumnType("float");

                    b.Property<string>("Cegempreendimento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Combustivel")
                        .HasColumnType("int");

                    b.Property<double>("FatorOperacaoComercial")
                        .HasColumnType("float");

                    b.Property<double>("FatorPerdasInternas")
                        .HasColumnType("float");

                    b.Property<int>("FonteEnergiaPrimaria")
                        .HasColumnType("int");

                    b.Property<double>("GarantiaFisicaCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<double>("GarantiaFisicaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoManutencaoReserveOperativaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoRestricaoOperacaoConstrainedOnMwm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoSegurancaEnergeticaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoTesteCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ParticipanteMre")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipanteRateioPerdas")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipanteRegimeCotas")
                        .HasColumnType("bit");

                    b.Property<double>("TaxaDescontoUsina")
                        .HasColumnType("float");

                    b.Property<int>("TipoDespacho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "IdPerfilAgente", "Mes");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("DadosGeracaoUsinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Encargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CompensacaoSincrona")
                        .HasColumnType("float");

                    b.Property<double>("DeslocamentoUsinaHidreletrica")
                        .HasColumnType("float");

                    b.Property<double>("DespachoSegurancaEnergetica")
                        .HasColumnType("float");

                    b.Property<double?>("EncargoImportacaoEnergia")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.Property<double>("OutrosServicosAncilares")
                        .HasColumnType("float");

                    b.Property<double>("RessarcimentoDeslocamento")
                        .HasColumnType("float");

                    b.Property<double>("RessarcimentoDespachoReservaPotenciaOperativa")
                        .HasColumnType("float");

                    b.Property<double>("RestricaoConstrainedOff")
                        .HasColumnType("float");

                    b.Property<double>("RestricaoConstrainedOn")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "IdPerfilAgente", "Mes");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("Encargos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.InfoMercadoArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InfoMercadoArquivos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ParcelaUsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaracteristicaParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInícioOperacaoComercialCcee")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsina")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsina");

                    b.ToTable("ParcelaUsinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.PerfilAgente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("IdAgente")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Submercado")
                        .HasColumnType("int");

                    b.Property<bool>("Varejista")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.HasIndex("IdAgente");

                    b.ToTable("PerfilAgentes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Usina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoAtivo")
                        .HasColumnType("int");

                    b.Property<string>("SiglaAtivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Submercado")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Usinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contabilizacao", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("Contabilizacaes")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contrato", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("Contratos")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.DadosGeracaoUsina", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("DadosGeracaoUsina")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("DadosGeracaoUsinas")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Encargo", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("Encargos")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("Encargos")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ParcelaUsina", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.Usina", "Usina")
                        .WithMany("ParcelasUsina")
                        .HasForeignKey("IdUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.PerfilAgente", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.Agente", "Agente")
                        .WithMany("PerfisAgente")
                        .HasForeignKey("IdAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Agente", b =>
                {
                    b.Navigation("PerfisAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ParcelaUsina", b =>
                {
                    b.Navigation("DadosGeracaoUsina");

                    b.Navigation("Encargos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.PerfilAgente", b =>
                {
                    b.Navigation("Contabilizacaes");

                    b.Navigation("Contratos");

                    b.Navigation("DadosGeracaoUsinas");

                    b.Navigation("Encargos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Usina", b =>
                {
                    b.Navigation("ParcelasUsina");
                });
#pragma warning restore 612, 618
        }
    }
}
