// <auto-generated />
using System;
using Infomercado.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infomercado.Domain.Migrations
{
    [DbContext(typeof(InfoMercadoDbContext))]
    [Migration("20210714005017_Consumo")]
    partial class Consumo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infomercado.Domain.Models.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("NomeEmpresarial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Cnpj");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ConsumoGeracaoPerfilAgente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ConsumoMWh")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("Mes", "IdPerfilAgente");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ConsumoGeracaoPerfilAgentes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ConsumoParcelaCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CapacidadeCargaMw")
                        .HasColumnType("float");

                    b.Property<string>("Carga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodigoCarga")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoPerfilDistribuidora")
                        .HasColumnType("int");

                    b.Property<double>("ConsumoAjustadoParcelaCargaMWh")
                        .HasColumnType("float");

                    b.Property<double>("ConsumoAjustadoParcelaCativaCargaLivreMWh")
                        .HasColumnType("float");

                    b.Property<double>("ConsumoAmbienteLivreMWh")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DataMigracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.Property<string>("RamoAtividade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SiglaPerfilDistribuidora")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Submercado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Mes", "IdPerfilAgente", "CodigoCarga");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ConsumoParcelaCargas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ConsumoPerfilAgente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Consumo")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.Property<int>("Patamar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Mes", "IdPerfilAgente", "Patamar");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ConsumoPerfilAgentes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contabilizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AjusteAlivioRetroativo")
                        .HasColumnType("float");

                    b.Property<double>("AjusteExposicaoFinanceira")
                        .HasColumnType("float");

                    b.Property<double>("AjusteMcsd")
                        .HasColumnType("float");

                    b.Property<double>("AjusteRecontabilizacoes")
                        .HasColumnType("float");

                    b.Property<double>("CompensacaoMre")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoCcearUsinasAptas")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContracaoPorDisponibilidade")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContratacaoComercializacaoEnergiaNuclear")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContratacaoCotaGarantiaFisica")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoContratacaoItaipu")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoCustosDeslocamentoPldeCmo")
                        .HasColumnType("float");

                    b.Property<double>("EfeitoRepasseRiscoHidrologico")
                        .HasColumnType("float");

                    b.Property<double>("EncargosConsolidados")
                        .HasColumnType("float");

                    b.Property<double>("ExcedenteFinanceiroEnergiaReserva")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<double>("ResultadoFinal")
                        .HasColumnType("float");

                    b.Property<double>("ResultadoMercadoCurtoPrazo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("MesAno", "IdPerfilAgente");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("Contabilizacaes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ContratacaoMWm")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdPerfilAgente", "Data", "Tipo");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.DadoMre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("GarantiaFisicaMWh")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<int>("Patamar")
                        .HasColumnType("int");

                    b.Property<int>("TipoMre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdPerfilAgente", "Data", "TipoMre", "Patamar");

                    b.ToTable("DadosMres");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.DadosGeracaoUsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CapacidadeUsinaMW")
                        .HasColumnType("float");

                    b.Property<string>("Cegempreendimento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Combustivel")
                        .HasColumnType("int");

                    b.Property<double>("FatorOperacaoComercial")
                        .HasColumnType("float");

                    b.Property<double>("FatorPerdasInternas")
                        .HasColumnType("float");

                    b.Property<int>("FonteEnergiaPrimaria")
                        .HasColumnType("int");

                    b.Property<double>("GarantiaFisicaCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<double>("GarantiaFisicaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoManutencaoReserveOperativaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoRestricaoOperacaoConstrainedOnMwm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoSegurancaEnergeticaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoTesteCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ParticipanteMre")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipanteRateioPerdas")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipanteRegimeCotas")
                        .HasColumnType("bit");

                    b.Property<double>("TaxaDescontoUsina")
                        .HasColumnType("float");

                    b.Property<int>("TipoDespacho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "IdPerfilAgente", "Mes");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("DadosGeracaoUsinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Encargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CompensacaoSincrona")
                        .HasColumnType("float");

                    b.Property<double>("DeslocamentoUsinaHidreletrica")
                        .HasColumnType("float");

                    b.Property<double>("DespachoSegurancaEnergetica")
                        .HasColumnType("float");

                    b.Property<double?>("EncargoImportacaoEnergia")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime2");

                    b.Property<double>("OutrosServicosAncilares")
                        .HasColumnType("float");

                    b.Property<double>("RessarcimentoDeslocamento")
                        .HasColumnType("float");

                    b.Property<double>("RessarcimentoDespachoReservaPotenciaOperativa")
                        .HasColumnType("float");

                    b.Property<double>("RestricaoConstrainedOff")
                        .HasColumnType("float");

                    b.Property<double>("RestricaoConstrainedOn")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "IdPerfilAgente", "Mes");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("Encargos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.GeracaoGarantiaFisicaUsinasParticipantesLeiloesDisponibilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CegeEmpreendimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("GarantiaFisicaComprometidaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GarantiaFisicaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoDestinadaLeilaoMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoLivreMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoMWm")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "MesAno");

                    b.ToTable("GeracaoGarantiaFisicaUsinasParticipantesLeiloesDisponibilidades");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.InfoMercadoArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InfoMercadoArquivos");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.LiquidacaoDistribuidoraCotistaGarantiaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CustosAdministrativosRs")
                        .HasColumnType("float");

                    b.Property<double>("FatorAdequacao")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<double>("ReceitaFixaAjustadaRs")
                        .HasColumnType("float");

                    b.Property<double>("ReceitaFixaPreliminarRs")
                        .HasColumnType("float");

                    b.Property<double>("ReceitaFixaTotalRs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "MesAno");

                    b.ToTable("CotistasLiquidacaoDistribuidoraGarantiaFisicas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.MontanteContratadoGarantiaFisicaComprometidaGeracaoDestinadaLeilaoDisponibilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CegeEmpreendimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("ContratosMWh")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataLeilao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FonteEnergiaPrimaria")
                        .HasColumnType("int");

                    b.Property<double>("GarantiaFisicaComprometidaMWm")
                        .HasColumnType("float");

                    b.Property<double>("GeracaoDestinadaLeilaoMWm")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<string>("Leilao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SiglaLeilao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "MesAno", "Leilao", "Produto", "CegeEmpreendimento");

                    b.ToTable("MontanteContratadoGarantiaFisicaComprometidaGeracaoDestinadaLeilaoDisponibilidades");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ParcelaUsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaracteristicaParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataInícioOperacaoComercialCcee")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsina")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsina");

                    b.ToTable("ParcelaUsinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.PerfilAgente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("IdAgente")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Submercado")
                        .HasColumnType("int");

                    b.Property<bool>("Varejista")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.HasIndex("IdAgente");

                    b.ToTable("PerfilAgentes");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ProinfaInformacoesConformeResolucao1833Usina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ccve")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("FonteEnergiaPrimaria")
                        .HasColumnType("int");

                    b.Property<double>("GeracaoCentroGravidadeMWm")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "Data");

                    b.ToTable("ProinfaInformacoesConformeResolucao1833Usinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ProinfaMontanteEnergiaAlocadaUsinasParticipantesMre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("FluxoEnergiaMreMWm")
                        .HasColumnType("float");

                    b.Property<int>("FonteEnergiaPrimaria")
                        .HasColumnType("int");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<bool>("ParticipanteMreEUsina")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdParcelaUsina", "IdPerfilAgente", "Data");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ProinfaMontanteEnergiaAlocadaUsinasParticipantesMres");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ReceitaVendaComercializacaoEnergiaNuclear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CustoAdministrativosRs")
                        .HasColumnType("float");

                    b.Property<double>("FatorAdequacao")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<double>("ReceitaFixaAjustadaRs")
                        .HasColumnType("float");

                    b.Property<double>("ReceitaFixaPreliminarRs")
                        .HasColumnType("float");

                    b.Property<double>("ReceitaVendaTotalRs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("MesAno", "IdPerfilAgente");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ReceitaVendaComercializacaoEnergiaNucleares");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ReceitaVendaDistribuidoraCotistaEnergiaNuclear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ajustes")
                        .HasColumnType("float");

                    b.Property<double>("FatorRateiroCotas")
                        .HasColumnType("float");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<double>("ReceitaVenda")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("MesAno", "IdPerfilAgente");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ReceitaVendaDistribuidoraCotistaEnergiaNucleares");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ReceitaVendaDistribuidoraCotistaGarantiaFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ajustes")
                        .HasColumnType("float");

                    b.Property<double>("FatorRateioCotas")
                        .HasColumnType("float");

                    b.Property<int>("IdParcelaUsina")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfilAgente")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("datetime2");

                    b.Property<double>("ReceitaVenda")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("MesAno", "IdPerfilAgente", "IdParcelaUsina");

                    b.HasIndex("IdParcelaUsina");

                    b.HasIndex("IdPerfilAgente");

                    b.ToTable("ReceitaVendaDistribuidoraCotistaGarantiaFisicas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Usina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoAtivo")
                        .HasColumnType("int");

                    b.Property<string>("SiglaAtivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Submercado")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Usinas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ConsumoGeracaoPerfilAgente", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ConsumoGeracaoPerfilAgentes")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ConsumoParcelaCarga", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ConsumoParcelaCargas")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ConsumoPerfilAgente", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ConsumoPerfilAgentes")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contabilizacao", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("Contabilizacaes")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Contrato", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("Contratos")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.DadoMre", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("DadosMres")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.DadosGeracaoUsina", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("DadosGeracaoUsina")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("DadosGeracaoUsinas")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Encargo", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("Encargos")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("Encargos")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.GeracaoGarantiaFisicaUsinasParticipantesLeiloesDisponibilidade", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("GeracaoGarantiaFisicaUsinasParticipantesLeiloesDisponibilidades")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.LiquidacaoDistribuidoraCotistaGarantiaFisica", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("LiquidacaoDistribuidoraCotistaGarantiaFisicas")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.MontanteContratadoGarantiaFisicaComprometidaGeracaoDestinadaLeilaoDisponibilidade", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("MontanteContratadoGarantiaFisicaComprometidaGeracaoDestinadaLeilaoDisponibilidades")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ParcelaUsina", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.Usina", "Usina")
                        .WithMany("ParcelasUsina")
                        .HasForeignKey("IdUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.PerfilAgente", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.Agente", "Agente")
                        .WithMany("PerfisAgente")
                        .HasForeignKey("IdAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ProinfaInformacoesConformeResolucao1833Usina", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("ProinfaInformacoesConformeResolucao1833Usinas")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ProinfaMontanteEnergiaAlocadaUsinasParticipantesMre", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("ProinfaMontanteEnergiaAlocadaUsinasParticipantesMres")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ProinfaMontanteEnergiaAlocadaUsinasParticipantesMres")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ReceitaVendaComercializacaoEnergiaNuclear", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ReceitaVendaComercializacaoEnergiaNucleares")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ReceitaVendaDistribuidoraCotistaEnergiaNuclear", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ReceitaVendaDistribuidoraCotistaEnergiaNucleares")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ReceitaVendaDistribuidoraCotistaGarantiaFisica", b =>
                {
                    b.HasOne("Infomercado.Domain.Models.ParcelaUsina", "ParcelaUsina")
                        .WithMany("ReceitaVendaDistribuidoraCotistaGarantiaFisicas")
                        .HasForeignKey("IdParcelaUsina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infomercado.Domain.Models.PerfilAgente", "PerfilAgente")
                        .WithMany("ReceitaVendaDistribuidoraCotistaGarantiaFisicas")
                        .HasForeignKey("IdPerfilAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaUsina");

                    b.Navigation("PerfilAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Agente", b =>
                {
                    b.Navigation("PerfisAgente");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.ParcelaUsina", b =>
                {
                    b.Navigation("DadosGeracaoUsina");

                    b.Navigation("Encargos");

                    b.Navigation("GeracaoGarantiaFisicaUsinasParticipantesLeiloesDisponibilidades");

                    b.Navigation("LiquidacaoDistribuidoraCotistaGarantiaFisicas");

                    b.Navigation("MontanteContratadoGarantiaFisicaComprometidaGeracaoDestinadaLeilaoDisponibilidades");

                    b.Navigation("ProinfaInformacoesConformeResolucao1833Usinas");

                    b.Navigation("ProinfaMontanteEnergiaAlocadaUsinasParticipantesMres");

                    b.Navigation("ReceitaVendaDistribuidoraCotistaGarantiaFisicas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.PerfilAgente", b =>
                {
                    b.Navigation("ConsumoGeracaoPerfilAgentes");

                    b.Navigation("ConsumoParcelaCargas");

                    b.Navigation("ConsumoPerfilAgentes");

                    b.Navigation("Contabilizacaes");

                    b.Navigation("Contratos");

                    b.Navigation("DadosGeracaoUsinas");

                    b.Navigation("DadosMres");

                    b.Navigation("Encargos");

                    b.Navigation("ProinfaMontanteEnergiaAlocadaUsinasParticipantesMres");

                    b.Navigation("ReceitaVendaComercializacaoEnergiaNucleares");

                    b.Navigation("ReceitaVendaDistribuidoraCotistaEnergiaNucleares");

                    b.Navigation("ReceitaVendaDistribuidoraCotistaGarantiaFisicas");
                });

            modelBuilder.Entity("Infomercado.Domain.Models.Usina", b =>
                {
                    b.Navigation("ParcelasUsina");
                });
#pragma warning restore 612, 618
        }
    }
}
